// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0fr8lU2Wo4Dqsd1VOLWwmV6lGz9c0R-c',
    appId: '1:200357723145:web:3bd9a0ea64427811cf8cd8',
    messagingSenderId: '200357723145',
    projectId: 'auralock-21da0',
    authDomain: 'auralock-21da0.firebaseapp.com',
    storageBucket: 'auralock-21da0.firebasestorage.app',
    measurementId: 'G-GZLDCHXPD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0YIwGgUdk5EDe7086Pw07TwVMCwDgWFw',
    appId: '1:200357723145:android:3137a501b142f9becf8cd8',
    messagingSenderId: '200357723145',
    projectId: 'auralock-21da0',
    storageBucket: 'auralock-21da0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrgSUOBrziWYx0JJ2FWSKY9MQhw-M675o',
    appId: '1:200357723145:ios:d5bd523a1a93ee32cf8cd8',
    messagingSenderId: '200357723145',
    projectId: 'auralock-21da0',
    storageBucket: 'auralock-21da0.firebasestorage.app',
    iosBundleId: 'com.example.auralockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrgSUOBrziWYx0JJ2FWSKY9MQhw-M675o',
    appId: '1:200357723145:ios:d5bd523a1a93ee32cf8cd8',
    messagingSenderId: '200357723145',
    projectId: 'auralock-21da0',
    storageBucket: 'auralock-21da0.firebasestorage.app',
    iosBundleId: 'com.example.auralockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0fr8lU2Wo4Dqsd1VOLWwmV6lGz9c0R-c',
    appId: '1:200357723145:web:4ba698cf9dc3d6a9cf8cd8',
    messagingSenderId: '200357723145',
    projectId: 'auralock-21da0',
    authDomain: 'auralock-21da0.firebaseapp.com',
    storageBucket: 'auralock-21da0.firebasestorage.app',
    measurementId: 'G-Z28EQ67EV7',
  );
}
